// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod regi_repl {

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_OPERATIONS: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_OPERATIONS: u8 = 8;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_OPERATIONS: [Operations; 9] = [
  Operations::NONE,
  Operations::SpiRead8Args,
  Operations::SpiRead16Args,
  Operations::SpiWrite8Args,
  Operations::SpiWrite16Args,
  Operations::I2cRead8Args,
  Operations::I2cRead16Args,
  Operations::I2cWrite8Args,
  Operations::I2cWrite16Args,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Operations(pub u8);
#[allow(non_upper_case_globals)]
impl Operations {
  pub const NONE: Self = Self(0);
  pub const SpiRead8Args: Self = Self(1);
  pub const SpiRead16Args: Self = Self(2);
  pub const SpiWrite8Args: Self = Self(3);
  pub const SpiWrite16Args: Self = Self(4);
  pub const I2cRead8Args: Self = Self(5);
  pub const I2cRead16Args: Self = Self(6);
  pub const I2cWrite8Args: Self = Self(7);
  pub const I2cWrite16Args: Self = Self(8);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 8;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::SpiRead8Args,
    Self::SpiRead16Args,
    Self::SpiWrite8Args,
    Self::SpiWrite16Args,
    Self::I2cRead8Args,
    Self::I2cRead16Args,
    Self::I2cWrite8Args,
    Self::I2cWrite16Args,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::SpiRead8Args => Some("SpiRead8Args"),
      Self::SpiRead16Args => Some("SpiRead16Args"),
      Self::SpiWrite8Args => Some("SpiWrite8Args"),
      Self::SpiWrite16Args => Some("SpiWrite16Args"),
      Self::I2cRead8Args => Some("I2cRead8Args"),
      Self::I2cRead16Args => Some("I2cRead16Args"),
      Self::I2cWrite8Args => Some("I2cWrite8Args"),
      Self::I2cWrite16Args => Some("I2cWrite16Args"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Operations {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Operations {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Operations {
    type Output = Operations;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Operations {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Operations {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Operations {}
pub struct OperationsUnionTableOffset {}

#[allow(clippy::upper_case_acronyms)]
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum OperationsT {
  NONE,
  SpiRead8Args(alloc::boxed::Box<SpiRead8ArgsT>),
  SpiRead16Args(alloc::boxed::Box<SpiRead16ArgsT>),
  SpiWrite8Args(alloc::boxed::Box<SpiWrite8ArgsT>),
  SpiWrite16Args(alloc::boxed::Box<SpiWrite16ArgsT>),
  I2cRead8Args(alloc::boxed::Box<I2cRead8ArgsT>),
  I2cRead16Args(alloc::boxed::Box<I2cRead16ArgsT>),
  I2cWrite8Args(alloc::boxed::Box<I2cWrite8ArgsT>),
  I2cWrite16Args(alloc::boxed::Box<I2cWrite16ArgsT>),
}
impl Default for OperationsT {
  fn default() -> Self {
    Self::NONE
  }
}
impl OperationsT {
  pub fn operations_type(&self) -> Operations {
    match self {
      Self::NONE => Operations::NONE,
      Self::SpiRead8Args(_) => Operations::SpiRead8Args,
      Self::SpiRead16Args(_) => Operations::SpiRead16Args,
      Self::SpiWrite8Args(_) => Operations::SpiWrite8Args,
      Self::SpiWrite16Args(_) => Operations::SpiWrite16Args,
      Self::I2cRead8Args(_) => Operations::I2cRead8Args,
      Self::I2cRead16Args(_) => Operations::I2cRead16Args,
      Self::I2cWrite8Args(_) => Operations::I2cWrite8Args,
      Self::I2cWrite16Args(_) => Operations::I2cWrite16Args,
    }
  }
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(&self, fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>) -> Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>> {
    match self {
      Self::NONE => None,
      Self::SpiRead8Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::SpiRead16Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::SpiWrite8Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::SpiWrite16Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::I2cRead8Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::I2cRead16Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::I2cWrite8Args(v) => Some(v.pack(fbb).as_union_value()),
      Self::I2cWrite16Args(v) => Some(v.pack(fbb).as_union_value()),
    }
  }
  /// If the union variant matches, return the owned SpiRead8ArgsT, setting the union to NONE.
  pub fn take_spi_read_8_args(&mut self) -> Option<alloc::boxed::Box<SpiRead8ArgsT>> {
    if let Self::SpiRead8Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::SpiRead8Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the SpiRead8ArgsT.
  pub fn as_spi_read_8_args(&self) -> Option<&SpiRead8ArgsT> {
    if let Self::SpiRead8Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the SpiRead8ArgsT.
  pub fn as_spi_read_8_args_mut(&mut self) -> Option<&mut SpiRead8ArgsT> {
    if let Self::SpiRead8Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned SpiRead16ArgsT, setting the union to NONE.
  pub fn take_spi_read_16_args(&mut self) -> Option<alloc::boxed::Box<SpiRead16ArgsT>> {
    if let Self::SpiRead16Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::SpiRead16Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the SpiRead16ArgsT.
  pub fn as_spi_read_16_args(&self) -> Option<&SpiRead16ArgsT> {
    if let Self::SpiRead16Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the SpiRead16ArgsT.
  pub fn as_spi_read_16_args_mut(&mut self) -> Option<&mut SpiRead16ArgsT> {
    if let Self::SpiRead16Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned SpiWrite8ArgsT, setting the union to NONE.
  pub fn take_spi_write_8_args(&mut self) -> Option<alloc::boxed::Box<SpiWrite8ArgsT>> {
    if let Self::SpiWrite8Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::SpiWrite8Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the SpiWrite8ArgsT.
  pub fn as_spi_write_8_args(&self) -> Option<&SpiWrite8ArgsT> {
    if let Self::SpiWrite8Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the SpiWrite8ArgsT.
  pub fn as_spi_write_8_args_mut(&mut self) -> Option<&mut SpiWrite8ArgsT> {
    if let Self::SpiWrite8Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned SpiWrite16ArgsT, setting the union to NONE.
  pub fn take_spi_write_16_args(&mut self) -> Option<alloc::boxed::Box<SpiWrite16ArgsT>> {
    if let Self::SpiWrite16Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::SpiWrite16Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the SpiWrite16ArgsT.
  pub fn as_spi_write_16_args(&self) -> Option<&SpiWrite16ArgsT> {
    if let Self::SpiWrite16Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the SpiWrite16ArgsT.
  pub fn as_spi_write_16_args_mut(&mut self) -> Option<&mut SpiWrite16ArgsT> {
    if let Self::SpiWrite16Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned I2cRead8ArgsT, setting the union to NONE.
  pub fn take_i2c_read_8_args(&mut self) -> Option<alloc::boxed::Box<I2cRead8ArgsT>> {
    if let Self::I2cRead8Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::I2cRead8Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the I2cRead8ArgsT.
  pub fn as_i2c_read_8_args(&self) -> Option<&I2cRead8ArgsT> {
    if let Self::I2cRead8Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the I2cRead8ArgsT.
  pub fn as_i2c_read_8_args_mut(&mut self) -> Option<&mut I2cRead8ArgsT> {
    if let Self::I2cRead8Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned I2cRead16ArgsT, setting the union to NONE.
  pub fn take_i2c_read_16_args(&mut self) -> Option<alloc::boxed::Box<I2cRead16ArgsT>> {
    if let Self::I2cRead16Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::I2cRead16Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the I2cRead16ArgsT.
  pub fn as_i2c_read_16_args(&self) -> Option<&I2cRead16ArgsT> {
    if let Self::I2cRead16Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the I2cRead16ArgsT.
  pub fn as_i2c_read_16_args_mut(&mut self) -> Option<&mut I2cRead16ArgsT> {
    if let Self::I2cRead16Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned I2cWrite8ArgsT, setting the union to NONE.
  pub fn take_i2c_write_8_args(&mut self) -> Option<alloc::boxed::Box<I2cWrite8ArgsT>> {
    if let Self::I2cWrite8Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::I2cWrite8Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the I2cWrite8ArgsT.
  pub fn as_i2c_write_8_args(&self) -> Option<&I2cWrite8ArgsT> {
    if let Self::I2cWrite8Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the I2cWrite8ArgsT.
  pub fn as_i2c_write_8_args_mut(&mut self) -> Option<&mut I2cWrite8ArgsT> {
    if let Self::I2cWrite8Args(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned I2cWrite16ArgsT, setting the union to NONE.
  pub fn take_i2c_write_16_args(&mut self) -> Option<alloc::boxed::Box<I2cWrite16ArgsT>> {
    if let Self::I2cWrite16Args(_) = self {
      let v = ::core::mem::replace(self, Self::NONE);
      if let Self::I2cWrite16Args(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the I2cWrite16ArgsT.
  pub fn as_i2c_write_16_args(&self) -> Option<&I2cWrite16ArgsT> {
    if let Self::I2cWrite16Args(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the I2cWrite16ArgsT.
  pub fn as_i2c_write_16_args_mut(&mut self) -> Option<&mut I2cWrite16ArgsT> {
    if let Self::I2cWrite16Args(v) = self { Some(v.as_mut()) } else { None }
  }
}
pub enum SpiRead8ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SpiRead8Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SpiRead8Args<'a> {
  type Inner = SpiRead8Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SpiRead8Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SpiRead8Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SpiRead8ArgsArgs
  ) -> ::flatbuffers::WIPOffset<SpiRead8Args<'bldr>> {
    let mut builder = SpiRead8ArgsBuilder::new(_fbb);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> SpiRead8ArgsT {
    let address = self.address();
    SpiRead8ArgsT {
      address,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiRead8Args::VT_ADDRESS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SpiRead8Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .finish();
    Ok(())
  }
}
pub struct SpiRead8ArgsArgs {
    pub address: u8,
}
impl<'a> Default for SpiRead8ArgsArgs {
  #[inline]
  fn default() -> Self {
    SpiRead8ArgsArgs {
      address: 0,
    }
  }
}

pub struct SpiRead8ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SpiRead8ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(SpiRead8Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SpiRead8ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SpiRead8ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SpiRead8Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SpiRead8Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SpiRead8Args");
      ds.field("address", &self.address());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct SpiRead8ArgsT {
  pub address: u8,
}
impl Default for SpiRead8ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
    }
  }
}
impl SpiRead8ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<SpiRead8Args<'b>> {
    let address = self.address;
    SpiRead8Args::create(_fbb, &SpiRead8ArgsArgs{
      address,
    })
  }
}
pub enum SpiRead16ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SpiRead16Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SpiRead16Args<'a> {
  type Inner = SpiRead16Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SpiRead16Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SpiRead16Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SpiRead16ArgsArgs
  ) -> ::flatbuffers::WIPOffset<SpiRead16Args<'bldr>> {
    let mut builder = SpiRead16ArgsBuilder::new(_fbb);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> SpiRead16ArgsT {
    let address = self.address();
    SpiRead16ArgsT {
      address,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiRead16Args::VT_ADDRESS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SpiRead16Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .finish();
    Ok(())
  }
}
pub struct SpiRead16ArgsArgs {
    pub address: u8,
}
impl<'a> Default for SpiRead16ArgsArgs {
  #[inline]
  fn default() -> Self {
    SpiRead16ArgsArgs {
      address: 0,
    }
  }
}

pub struct SpiRead16ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SpiRead16ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(SpiRead16Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SpiRead16ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SpiRead16ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SpiRead16Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SpiRead16Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SpiRead16Args");
      ds.field("address", &self.address());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct SpiRead16ArgsT {
  pub address: u8,
}
impl Default for SpiRead16ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
    }
  }
}
impl SpiRead16ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<SpiRead16Args<'b>> {
    let address = self.address;
    SpiRead16Args::create(_fbb, &SpiRead16ArgsArgs{
      address,
    })
  }
}
pub enum SpiWrite8ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SpiWrite8Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SpiWrite8Args<'a> {
  type Inner = SpiWrite8Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SpiWrite8Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE1: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SpiWrite8Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SpiWrite8ArgsArgs
  ) -> ::flatbuffers::WIPOffset<SpiWrite8Args<'bldr>> {
    let mut builder = SpiWrite8ArgsBuilder::new(_fbb);
    builder.add_value1(args.value1);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> SpiWrite8ArgsT {
    let address = self.address();
    let value1 = self.value1();
    SpiWrite8ArgsT {
      address,
      value1,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiWrite8Args::VT_ADDRESS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value1(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiWrite8Args::VT_VALUE1, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SpiWrite8Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .visit_field::<u8>("value1", Self::VT_VALUE1, false)?
     .finish();
    Ok(())
  }
}
pub struct SpiWrite8ArgsArgs {
    pub address: u8,
    pub value1: u8,
}
impl<'a> Default for SpiWrite8ArgsArgs {
  #[inline]
  fn default() -> Self {
    SpiWrite8ArgsArgs {
      address: 0,
      value1: 0,
    }
  }
}

pub struct SpiWrite8ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SpiWrite8ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(SpiWrite8Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn add_value1(&mut self, value1: u8) {
    self.fbb_.push_slot::<u8>(SpiWrite8Args::VT_VALUE1, value1, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SpiWrite8ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SpiWrite8ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SpiWrite8Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SpiWrite8Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SpiWrite8Args");
      ds.field("address", &self.address());
      ds.field("value1", &self.value1());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct SpiWrite8ArgsT {
  pub address: u8,
  pub value1: u8,
}
impl Default for SpiWrite8ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
      value1: 0,
    }
  }
}
impl SpiWrite8ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<SpiWrite8Args<'b>> {
    let address = self.address;
    let value1 = self.value1;
    SpiWrite8Args::create(_fbb, &SpiWrite8ArgsArgs{
      address,
      value1,
    })
  }
}
pub enum SpiWrite16ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SpiWrite16Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SpiWrite16Args<'a> {
  type Inner = SpiWrite16Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SpiWrite16Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE1: ::flatbuffers::VOffsetT = 6;
  pub const VT_VALUE2: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SpiWrite16Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SpiWrite16ArgsArgs
  ) -> ::flatbuffers::WIPOffset<SpiWrite16Args<'bldr>> {
    let mut builder = SpiWrite16ArgsBuilder::new(_fbb);
    builder.add_value2(args.value2);
    builder.add_value1(args.value1);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> SpiWrite16ArgsT {
    let address = self.address();
    let value1 = self.value1();
    let value2 = self.value2();
    SpiWrite16ArgsT {
      address,
      value1,
      value2,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiWrite16Args::VT_ADDRESS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value1(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiWrite16Args::VT_VALUE1, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value2(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SpiWrite16Args::VT_VALUE2, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SpiWrite16Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .visit_field::<u8>("value1", Self::VT_VALUE1, false)?
     .visit_field::<u8>("value2", Self::VT_VALUE2, false)?
     .finish();
    Ok(())
  }
}
pub struct SpiWrite16ArgsArgs {
    pub address: u8,
    pub value1: u8,
    pub value2: u8,
}
impl<'a> Default for SpiWrite16ArgsArgs {
  #[inline]
  fn default() -> Self {
    SpiWrite16ArgsArgs {
      address: 0,
      value1: 0,
      value2: 0,
    }
  }
}

pub struct SpiWrite16ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SpiWrite16ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(SpiWrite16Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn add_value1(&mut self, value1: u8) {
    self.fbb_.push_slot::<u8>(SpiWrite16Args::VT_VALUE1, value1, 0);
  }
  #[inline]
  pub fn add_value2(&mut self, value2: u8) {
    self.fbb_.push_slot::<u8>(SpiWrite16Args::VT_VALUE2, value2, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SpiWrite16ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SpiWrite16ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SpiWrite16Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SpiWrite16Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SpiWrite16Args");
      ds.field("address", &self.address());
      ds.field("value1", &self.value1());
      ds.field("value2", &self.value2());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct SpiWrite16ArgsT {
  pub address: u8,
  pub value1: u8,
  pub value2: u8,
}
impl Default for SpiWrite16ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
      value1: 0,
      value2: 0,
    }
  }
}
impl SpiWrite16ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<SpiWrite16Args<'b>> {
    let address = self.address;
    let value1 = self.value1;
    let value2 = self.value2;
    SpiWrite16Args::create(_fbb, &SpiWrite16ArgsArgs{
      address,
      value1,
      value2,
    })
  }
}
pub enum I2cRead8ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct I2cRead8Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for I2cRead8Args<'a> {
  type Inner = I2cRead8Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> I2cRead8Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    I2cRead8Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args I2cRead8ArgsArgs
  ) -> ::flatbuffers::WIPOffset<I2cRead8Args<'bldr>> {
    let mut builder = I2cRead8ArgsBuilder::new(_fbb);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> I2cRead8ArgsT {
    let address = self.address();
    I2cRead8ArgsT {
      address,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cRead8Args::VT_ADDRESS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for I2cRead8Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .finish();
    Ok(())
  }
}
pub struct I2cRead8ArgsArgs {
    pub address: u8,
}
impl<'a> Default for I2cRead8ArgsArgs {
  #[inline]
  fn default() -> Self {
    I2cRead8ArgsArgs {
      address: 0,
    }
  }
}

pub struct I2cRead8ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> I2cRead8ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(I2cRead8Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> I2cRead8ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    I2cRead8ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<I2cRead8Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for I2cRead8Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("I2cRead8Args");
      ds.field("address", &self.address());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct I2cRead8ArgsT {
  pub address: u8,
}
impl Default for I2cRead8ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
    }
  }
}
impl I2cRead8ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<I2cRead8Args<'b>> {
    let address = self.address;
    I2cRead8Args::create(_fbb, &I2cRead8ArgsArgs{
      address,
    })
  }
}
pub enum I2cRead16ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct I2cRead16Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for I2cRead16Args<'a> {
  type Inner = I2cRead16Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> I2cRead16Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    I2cRead16Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args I2cRead16ArgsArgs
  ) -> ::flatbuffers::WIPOffset<I2cRead16Args<'bldr>> {
    let mut builder = I2cRead16ArgsBuilder::new(_fbb);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> I2cRead16ArgsT {
    let address = self.address();
    I2cRead16ArgsT {
      address,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cRead16Args::VT_ADDRESS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for I2cRead16Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .finish();
    Ok(())
  }
}
pub struct I2cRead16ArgsArgs {
    pub address: u8,
}
impl<'a> Default for I2cRead16ArgsArgs {
  #[inline]
  fn default() -> Self {
    I2cRead16ArgsArgs {
      address: 0,
    }
  }
}

pub struct I2cRead16ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> I2cRead16ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(I2cRead16Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> I2cRead16ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    I2cRead16ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<I2cRead16Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for I2cRead16Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("I2cRead16Args");
      ds.field("address", &self.address());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct I2cRead16ArgsT {
  pub address: u8,
}
impl Default for I2cRead16ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
    }
  }
}
impl I2cRead16ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<I2cRead16Args<'b>> {
    let address = self.address;
    I2cRead16Args::create(_fbb, &I2cRead16ArgsArgs{
      address,
    })
  }
}
pub enum I2cWrite8ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct I2cWrite8Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for I2cWrite8Args<'a> {
  type Inner = I2cWrite8Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> I2cWrite8Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE1: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    I2cWrite8Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args I2cWrite8ArgsArgs
  ) -> ::flatbuffers::WIPOffset<I2cWrite8Args<'bldr>> {
    let mut builder = I2cWrite8ArgsBuilder::new(_fbb);
    builder.add_value1(args.value1);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> I2cWrite8ArgsT {
    let address = self.address();
    let value1 = self.value1();
    I2cWrite8ArgsT {
      address,
      value1,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cWrite8Args::VT_ADDRESS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value1(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cWrite8Args::VT_VALUE1, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for I2cWrite8Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .visit_field::<u8>("value1", Self::VT_VALUE1, false)?
     .finish();
    Ok(())
  }
}
pub struct I2cWrite8ArgsArgs {
    pub address: u8,
    pub value1: u8,
}
impl<'a> Default for I2cWrite8ArgsArgs {
  #[inline]
  fn default() -> Self {
    I2cWrite8ArgsArgs {
      address: 0,
      value1: 0,
    }
  }
}

pub struct I2cWrite8ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> I2cWrite8ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(I2cWrite8Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn add_value1(&mut self, value1: u8) {
    self.fbb_.push_slot::<u8>(I2cWrite8Args::VT_VALUE1, value1, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> I2cWrite8ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    I2cWrite8ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<I2cWrite8Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for I2cWrite8Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("I2cWrite8Args");
      ds.field("address", &self.address());
      ds.field("value1", &self.value1());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct I2cWrite8ArgsT {
  pub address: u8,
  pub value1: u8,
}
impl Default for I2cWrite8ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
      value1: 0,
    }
  }
}
impl I2cWrite8ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<I2cWrite8Args<'b>> {
    let address = self.address;
    let value1 = self.value1;
    I2cWrite8Args::create(_fbb, &I2cWrite8ArgsArgs{
      address,
      value1,
    })
  }
}
pub enum I2cWrite16ArgsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct I2cWrite16Args<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for I2cWrite16Args<'a> {
  type Inner = I2cWrite16Args<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> I2cWrite16Args<'a> {
  pub const VT_ADDRESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE1: ::flatbuffers::VOffsetT = 6;
  pub const VT_VALUE2: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    I2cWrite16Args { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args I2cWrite16ArgsArgs
  ) -> ::flatbuffers::WIPOffset<I2cWrite16Args<'bldr>> {
    let mut builder = I2cWrite16ArgsBuilder::new(_fbb);
    builder.add_value2(args.value2);
    builder.add_value1(args.value1);
    builder.add_address(args.address);
    builder.finish()
  }

  pub fn unpack(&self) -> I2cWrite16ArgsT {
    let address = self.address();
    let value1 = self.value1();
    let value2 = self.value2();
    I2cWrite16ArgsT {
      address,
      value1,
      value2,
    }
  }

  #[inline]
  pub fn address(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cWrite16Args::VT_ADDRESS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value1(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cWrite16Args::VT_VALUE1, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value2(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(I2cWrite16Args::VT_VALUE2, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for I2cWrite16Args<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("address", Self::VT_ADDRESS, false)?
     .visit_field::<u8>("value1", Self::VT_VALUE1, false)?
     .visit_field::<u8>("value2", Self::VT_VALUE2, false)?
     .finish();
    Ok(())
  }
}
pub struct I2cWrite16ArgsArgs {
    pub address: u8,
    pub value1: u8,
    pub value2: u8,
}
impl<'a> Default for I2cWrite16ArgsArgs {
  #[inline]
  fn default() -> Self {
    I2cWrite16ArgsArgs {
      address: 0,
      value1: 0,
      value2: 0,
    }
  }
}

pub struct I2cWrite16ArgsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> I2cWrite16ArgsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_address(&mut self, address: u8) {
    self.fbb_.push_slot::<u8>(I2cWrite16Args::VT_ADDRESS, address, 0);
  }
  #[inline]
  pub fn add_value1(&mut self, value1: u8) {
    self.fbb_.push_slot::<u8>(I2cWrite16Args::VT_VALUE1, value1, 0);
  }
  #[inline]
  pub fn add_value2(&mut self, value2: u8) {
    self.fbb_.push_slot::<u8>(I2cWrite16Args::VT_VALUE2, value2, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> I2cWrite16ArgsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    I2cWrite16ArgsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<I2cWrite16Args<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for I2cWrite16Args<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("I2cWrite16Args");
      ds.field("address", &self.address());
      ds.field("value1", &self.value1());
      ds.field("value2", &self.value2());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct I2cWrite16ArgsT {
  pub address: u8,
  pub value1: u8,
  pub value2: u8,
}
impl Default for I2cWrite16ArgsT {
  fn default() -> Self {
    Self {
      address: 0,
      value1: 0,
      value2: 0,
    }
  }
}
impl I2cWrite16ArgsT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<I2cWrite16Args<'b>> {
    let address = self.address;
    let value1 = self.value1;
    let value2 = self.value2;
    I2cWrite16Args::create(_fbb, &I2cWrite16ArgsArgs{
      address,
      value1,
      value2,
    })
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Message<'a> {
  pub const VT_OPERATIONS_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_OPERATIONS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageArgs
  ) -> ::flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.operations { builder.add_operations(x); }
    builder.add_operations_type(args.operations_type);
    builder.finish()
  }

  pub fn unpack(&self) -> MessageT {
    let operations = match self.operations_type() {
      Operations::NONE => OperationsT::NONE,
      Operations::SpiRead8Args => OperationsT::SpiRead8Args(alloc::boxed::Box::new(
        self.operations_as_spi_read_8_args()
            .expect("Invalid union table, expected `Operations::SpiRead8Args`.")
            .unpack()
      )),
      Operations::SpiRead16Args => OperationsT::SpiRead16Args(alloc::boxed::Box::new(
        self.operations_as_spi_read_16_args()
            .expect("Invalid union table, expected `Operations::SpiRead16Args`.")
            .unpack()
      )),
      Operations::SpiWrite8Args => OperationsT::SpiWrite8Args(alloc::boxed::Box::new(
        self.operations_as_spi_write_8_args()
            .expect("Invalid union table, expected `Operations::SpiWrite8Args`.")
            .unpack()
      )),
      Operations::SpiWrite16Args => OperationsT::SpiWrite16Args(alloc::boxed::Box::new(
        self.operations_as_spi_write_16_args()
            .expect("Invalid union table, expected `Operations::SpiWrite16Args`.")
            .unpack()
      )),
      Operations::I2cRead8Args => OperationsT::I2cRead8Args(alloc::boxed::Box::new(
        self.operations_as_i2c_read_8_args()
            .expect("Invalid union table, expected `Operations::I2cRead8Args`.")
            .unpack()
      )),
      Operations::I2cRead16Args => OperationsT::I2cRead16Args(alloc::boxed::Box::new(
        self.operations_as_i2c_read_16_args()
            .expect("Invalid union table, expected `Operations::I2cRead16Args`.")
            .unpack()
      )),
      Operations::I2cWrite8Args => OperationsT::I2cWrite8Args(alloc::boxed::Box::new(
        self.operations_as_i2c_write_8_args()
            .expect("Invalid union table, expected `Operations::I2cWrite8Args`.")
            .unpack()
      )),
      Operations::I2cWrite16Args => OperationsT::I2cWrite16Args(alloc::boxed::Box::new(
        self.operations_as_i2c_write_16_args()
            .expect("Invalid union table, expected `Operations::I2cWrite16Args`.")
            .unpack()
      )),
      _ => OperationsT::NONE,
    };
    MessageT {
      operations,
    }
  }

  #[inline]
  pub fn operations_type(&self) -> Operations {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Operations>(Message::VT_OPERATIONS_TYPE, Some(Operations::NONE)).unwrap()}
  }
  #[inline]
  pub fn operations(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Message::VT_OPERATIONS, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_spi_read_8_args(&self) -> Option<SpiRead8Args<'a>> {
    if self.operations_type() == Operations::SpiRead8Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SpiRead8Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_spi_read_16_args(&self) -> Option<SpiRead16Args<'a>> {
    if self.operations_type() == Operations::SpiRead16Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SpiRead16Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_spi_write_8_args(&self) -> Option<SpiWrite8Args<'a>> {
    if self.operations_type() == Operations::SpiWrite8Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SpiWrite8Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_spi_write_16_args(&self) -> Option<SpiWrite16Args<'a>> {
    if self.operations_type() == Operations::SpiWrite16Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SpiWrite16Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_i2c_read_8_args(&self) -> Option<I2cRead8Args<'a>> {
    if self.operations_type() == Operations::I2cRead8Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { I2cRead8Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_i2c_read_16_args(&self) -> Option<I2cRead16Args<'a>> {
    if self.operations_type() == Operations::I2cRead16Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { I2cRead16Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_i2c_write_8_args(&self) -> Option<I2cWrite8Args<'a>> {
    if self.operations_type() == Operations::I2cWrite8Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { I2cWrite8Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn operations_as_i2c_write_16_args(&self) -> Option<I2cWrite16Args<'a>> {
    if self.operations_type() == Operations::I2cWrite16Args {
      self.operations().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { I2cWrite16Args::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<Operations, _>("operations_type", Self::VT_OPERATIONS_TYPE, "operations", Self::VT_OPERATIONS, false, |key, v, pos| {
        match key {
          Operations::SpiRead8Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SpiRead8Args>>("Operations::SpiRead8Args", pos),
          Operations::SpiRead16Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SpiRead16Args>>("Operations::SpiRead16Args", pos),
          Operations::SpiWrite8Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SpiWrite8Args>>("Operations::SpiWrite8Args", pos),
          Operations::SpiWrite16Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SpiWrite16Args>>("Operations::SpiWrite16Args", pos),
          Operations::I2cRead8Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<I2cRead8Args>>("Operations::I2cRead8Args", pos),
          Operations::I2cRead16Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<I2cRead16Args>>("Operations::I2cRead16Args", pos),
          Operations::I2cWrite8Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<I2cWrite8Args>>("Operations::I2cWrite8Args", pos),
          Operations::I2cWrite16Args => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<I2cWrite16Args>>("Operations::I2cWrite16Args", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs {
    pub operations_type: Operations,
    pub operations: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for MessageArgs {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      operations_type: Operations::NONE,
      operations: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_operations_type(&mut self, operations_type: Operations) {
    self.fbb_.push_slot::<Operations>(Message::VT_OPERATIONS_TYPE, operations_type, Operations::NONE);
  }
  #[inline]
  pub fn add_operations(&mut self, operations: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Message::VT_OPERATIONS, operations);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("operations_type", &self.operations_type());
      match self.operations_type() {
        Operations::SpiRead8Args => {
          if let Some(x) = self.operations_as_spi_read_8_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::SpiRead16Args => {
          if let Some(x) = self.operations_as_spi_read_16_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::SpiWrite8Args => {
          if let Some(x) = self.operations_as_spi_write_8_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::SpiWrite16Args => {
          if let Some(x) = self.operations_as_spi_write_16_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::I2cRead8Args => {
          if let Some(x) = self.operations_as_i2c_read_8_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::I2cRead16Args => {
          if let Some(x) = self.operations_as_i2c_read_16_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::I2cWrite8Args => {
          if let Some(x) = self.operations_as_i2c_write_8_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Operations::I2cWrite16Args => {
          if let Some(x) = self.operations_as_i2c_write_16_args() {
            ds.field("operations", &x)
          } else {
            ds.field("operations", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("operations", &x)
        },
      };
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct MessageT {
  pub operations: OperationsT,
}
impl Default for MessageT {
  fn default() -> Self {
    Self {
      operations: OperationsT::NONE,
    }
  }
}
impl MessageT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<Message<'b>> {
    let operations_type = self.operations.operations_type();
    let operations = self.operations.pack(_fbb);
    Message::create(_fbb, &MessageArgs{
      operations_type,
      operations,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Message`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message(buf: &[u8]) -> Result<Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Message>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_message_unchecked`.
pub fn size_prefixed_root_as_message(buf: &[u8]) -> Result<Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Message>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Message` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn size_prefixed_root_as_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Message`.
pub unsafe fn root_as_message_unchecked(buf: &[u8]) -> Message<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Message>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Message`.
pub unsafe fn size_prefixed_root_as_message_unchecked(buf: &[u8]) -> Message<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Message>(buf) }
}
#[inline]
pub fn finish_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod RegiRepl

