import { MainContent } from "./main_content.slint";
import { HomeSlintStore } from "../stores/home_slint_store.slint";
import { Icons } from "../../../../../material-ui-slint/ui/icons/icons.slint";
import { Max31865SlintErr } from "../models/enum_temperature_err.slint";
import {
    MaterialText,
    Icon,
} from "../../../../../material-ui-slint/material.slint";

import {
    MaterialTypography,
    HorizontalDivider,
    Badge,
    BadgeWithColor,
} from  "../../../../../material-ui-slint/material.slint";
import { SettingStoreSlint } from "../stores/setting_store.slint";
import { Units } from "../models/enum_unit.slint";

export component Home inherits MainContent {

    function getUnit() -> string {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return " C";
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return " R";
        } else {
            return " F";
        }
    }

    function getErrorMessage() -> string {
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.SPI_FailToRead) {
            return "Fail When Read Spi";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.SPI_FailToWrite) {
            return "Fail When Write Spi";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.Hardware_OverOrUnderVoltage) {
            return "Over Or Under Voltage";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.Hardware_RtdinForceMinusOpen) {
            return "RTD in force minus open";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.Hardware_RefinForceMinusOpen) {
            return "REFIN force minus open";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.Hardware_RefinGreatherThanPoint85TimeVBias) {
            return "Refin Greather than 0.85 * VBias";
        }
        if (HomeSlintStore.max31865Err.value == Max31865SlintErr.Hardware-RtdLowThreshold) {
            return "RTD Low Threshold";
        } else {
            return "RTD High Threshold";
        }
    }

    Rectangle {
        background: @linear-gradient(90deg, #1E4A59 0%, #135D6E 60%, #127FA3 100%);
        HorizontalLayout {
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 5px;
            alignment: start;
            Icon {
                source: HomeSlintStore.isCharging ? Icons.battery_charging : Icons.battery;
                colorize: white;
            }

            MaterialText {
                font-weight: 1000;
                text: HomeSlintStore.isCharging ? "Charging..." : "Not Charging";
                color: white;
            }
        }
    }

    HorizontalDivider { }

    VerticalLayout {
        alignment: center;
        width: 160px;

        HorizontalLayout {
            alignment: center;

            if HomeSlintStore.max31865Err.hasValue: 
              MaterialText {
                text: getErrorMessage();
                font-size: 20px;
                color: red;
            }

            if !HomeSlintStore.max31865Err.hasValue: 
              MaterialText {
                text: HomeSlintStore.temperature + getUnit();
                font-size: 30px;
            }
        }
    }
}
