import { MainContent } from "./main_content.slint";
import { HomeSlintStore } from "../stores/home_slint_store.slint";
import { Icons } from "../../../../../material-ui-slint/ui/icons/icons.slint";
import {
    MaterialText,
    Icon,
} from "../../../../../material-ui-slint/material.slint";

import {
    MaterialTypography,
    HorizontalDivider,
    Badge,
    BadgeWithColor,
} from  "../../../../../material-ui-slint/material.slint";
import { SettingStoreSlint } from "../stores/setting_store.slint";
import { Units } from "../models/enum_unit.slint";
import { GlobalStore } from "../stores/global_store.slint";
import { Tabs } from "../models/enum_tabs.slint";

export component Home inherits MainContent {

    visible: GlobalStore.activeTab == Tabs.Home;

    function getUnit() -> string {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return " C";
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return " R";
        } else {
            return " F";
        }
    }

    HorizontalLayout {
        padding-bottom: 10px;
        alignment: end;
        MaterialText {
            text: HomeSlintStore.isCharging ? "Charging..." : "Not Charging";
        }

        Icon {
            source: HomeSlintStore.isCharging ? Icons.battery_charging : Icons.battery;
        }
    }

    HorizontalDivider { }

    VerticalLayout {
        alignment: center;
        width: 160px;

        HorizontalLayout {
            alignment: center;
            MaterialText {
                text: HomeSlintStore.temperature + getUnit();
                font-size: 30px;
            }
        }
    }

    HorizontalLayout {
        alignment: end;
        BadgeWithColor {
            text: "Home";
            bgColor: blue;
        }
    }
}
