import { MainContent } from "./main_content.slint";
import { HomeSlintStore } from "../stores/home_slint_store.slint";
import { BleOptionSlintStore } from "../stores/ble_option_store.slint";
import { SettingStoreSlint } from "../stores/setting_store.slint";
import { Icons } from "../../../../../material-ui-slint/ui/icons/icons.slint";
import {
    MaterialText,
    Icon,
} from "../../../../../material-ui-slint/material.slint";

import {
    MaterialTypography,
    HorizontalDivider,
    FilledButton,
    IconButton,
    BadgeWithColor,
} from  "../../../../../material-ui-slint/material.slint";
import { SettingStoreSlint } from "../stores/setting_store.slint";
import { Units } from "../models/enum_unit.slint";
import {
    Badge,
} from "../../../../../material-ui-slint/ui/components/badge.slint";

export component UnitSetting inherits MainContent {

    function getUnit() -> string {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return "Celcius";
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return "Reamur";
        } else {
            return "Fahrenheit";
        }
    }

    function getNextUnit() -> string {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return "Reamur";
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return "Fahrenheit";
        } else {
            return "Celcius";
        }
    }

    function getPrevUnit() -> string {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return "Fahrenheit";
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return "Celcius";
        } else {
            return "Reamur";
        }
    }

    function getBgColor() -> brush {
        if SettingStoreSlint.selectedUnit == Units.Celcius {
            return @linear-gradient(90deg, #591E35 0%, #6E1342 60%, #A3127F 100%);
        } else if SettingStoreSlint.selectedUnit == Units.Reamur {
            return @linear-gradient(90deg, #59361E 0%, #6E4B13 60%, #BAAC0B 100%);
        } else {
            return @linear-gradient(90deg, #1E5920 0%, #136E21 60%, #25BA0B 100%);
        }
    }

    Rectangle {
        background: @linear-gradient(90deg, #1E4A59 0%, #135D6E 60%, #127FA3 100%);
        HorizontalLayout {
            padding-bottom: 10px;
            padding-left: 5px;
            padding-top: 10px;
            alignment: start;

            Icon {
                source: Icons.scale;
                colorize: white;
            }

            MaterialText {
                text: " Selected Unit";
                color: white;
            }
        }
    }

    HorizontalDivider { }

    VerticalLayout {
        width: 160px;
        alignment: center;

        VerticalLayout {
            padding-top: 10px;

            HorizontalLayout {
                IconButton {
                    inline: true;
                    icon: Icons.arrow_left;
                }

                HorizontalLayout {
                    alignment: center;
                    MaterialText {
                        text: getPrevUnit();
                        style: MaterialTypography.label_small;
                    }
                }
            }

            Rectangle {
                background: getBgColor();
                VerticalLayout {
                    alignment: center;

                    HorizontalLayout {
                        alignment: center;
                        MaterialText {
                            text: getUnit();
                            style: MaterialTypography.title_large_bold;
                            color: white;
                        }
                    }
                }
            }

            HorizontalLayout {
                HorizontalLayout {
                    alignment: center;
                    MaterialText {
                        text: getNextUnit();
                        style: MaterialTypography.label_small;
                    }
                }

                IconButton {
                    inline: true;
                    icon: Icons.arrow_right;
                }
            }
        }
    }
}
